[build]
  publish = "."

[[headers]]
  for = "/_data/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Cache-Control = "no-cache, no-store, must-revalidate"

[[headers]]
  for = "/images/uploads/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
    Access-Control-Allow-Origin = "*"

[[redirects]]
  from = "/admin"
  to = "/admin/index.html"
  status = 200
